# Form implementation generated from reading ui file 'XO_Game.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from styleset import StyleSheet
from gameback import GameCheck


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:#003049;\n"
"")
        self.cur_play=1 #Bu  Degani X yuradi 
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 450, 169, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:#669bbc;\n"
"color:#fdf0d5;\n"
"border-radius:10px;\n"
"border-color:#fdf0d5")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 450, 169, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:#669bbc;\n"
"color:#fdf0d5;\n"
"border-radius:10px;\n"
"border-color:#fdf0d5")
        
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(QApplication.quit)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 761, 441))
        self.tabWidget.setStyleSheet("background-color:#780000;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 30, 131, 121))
        self.pushButton_3.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 30, 131, 121))
        self.pushButton_4.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 30, 131, 121))
        self.pushButton_5.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 150, 131, 121))
        self.pushButton_6.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 150, 131, 121))
        self.pushButton_7.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(440, 150, 131, 121))
        self.pushButton_8.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(180, 270, 131, 121))
        self.pushButton_9.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(310, 270, 131, 121))
        self.pushButton_10.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(440, 270, 131, 121))
        self.pushButton_11.setStyleSheet("background-color:#003049;\n"
"color:#fdf0d5;")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(50, 30, 111, 361))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:#c1121f;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setGeometry(QtCore.QRect(600, 30, 111, 361))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#c1121f;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(parent=self.menubar)
        self.menuGame.setObjectName("menuGame")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)

        self.btn_lst=[
            self.pushButton_3,
            self.pushButton_4,
            self.pushButton_5,
            self.pushButton_6,
            self.pushButton_7,
            self.pushButton_8,
            self.pushButton_9,
            self.pushButton_10,
            self.pushButton_11
        ]
        self.btn_lst[0].clicked.connect(lambda:self.click_btn(0))
        self.pushButton_4.clicked.connect(lambda:self.click_btn(1))
        self.pushButton_5.clicked.connect(lambda:self.click_btn(2))
        self.pushButton_6.clicked.connect(lambda:self.click_btn(3))
        self.pushButton_7.clicked.connect(lambda:self.click_btn(4))
        self.pushButton_8.clicked.connect(lambda:self.click_btn(5))
        self.pushButton_9.clicked.connect(lambda:self.click_btn(6))
        self.pushButton_10.clicked.connect(lambda:self.click_btn(7))
        self.pushButton_11.clicked.connect(lambda:self.click_btn(8))
        self.pushButton_2.clicked.connect(self.restart)
        self.gm_check=GameCheck(self.btn_lst)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Start"))
        self.pushButton.setText(_translate("MainWindow", "Quit"))
        self.label.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "o"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuGame.setTitle(_translate("MainWindow", "Game"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        
    def restart(self):
        for btn in self.btn_lst:
            btn.setText("")
            btn.setEnabled(True)
        self.label.setStyleSheet(StyleSheet.activate())
        self.label_2.setStyleSheet(StyleSheet.not_active())

    def click_btn(self,num:int):
        if self.cur_play == 1:
            self.btn_lst[num].setText("X")
            self.btn_lst[num].setStyleSheet("font-size:50px;")
            self.btn_lst[num].setEnabled(False)
            self.cur_play=0
            self.label_2.setStyleSheet(StyleSheet.activate())
            self.label.setStyleSheet(StyleSheet.not_active())
        else:
            self.btn_lst[num].setText("O")
            self.btn_lst[num].setStyleSheet("font-size:50px;")
            self.btn_lst[num].setEnabled(False)
            self.cur_play=1
            self.label.setStyleSheet(StyleSheet.activate())
            self.label_2.setStyleSheet(StyleSheet.not_active())

        ans=self.gm_check.check_winer()
        if ans!=None:
                QMessageBox.information(None,"Tabriklaymiz",ans+" Siz G'olib bo'ldingiz ")        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
